/*
 * generated by Xtext
 */
package edu.ksu.cis.projects.mdcf.devicemodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DeviceModelingLanguageUiModule extends edu.ksu.cis.projects.mdcf.devicemodel.ui.AbstractDeviceModelingLanguageUiModule {
	public DeviceModelingLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
