/*
* generated by Xtext
*/
package edu.ksu.cis.projects.mdcf.devicemodel.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import edu.ksu.cis.projects.mdcf.devicemodel.services.DeviceModelingLanguageGrammarAccess;

public class DeviceModelingLanguageParser extends AbstractContentAssistParser {
	
	@Inject
	private DeviceModelingLanguageGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected edu.ksu.cis.projects.mdcf.devicemodel.ui.contentassist.antlr.internal.InternalDeviceModelingLanguageParser createParser() {
		edu.ksu.cis.projects.mdcf.devicemodel.ui.contentassist.antlr.internal.InternalDeviceModelingLanguageParser result = new edu.ksu.cis.projects.mdcf.devicemodel.ui.contentassist.antlr.internal.InternalDeviceModelingLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDeclAccess().getAlternatives(), "rule__Decl__Alternatives");
					put(grammarAccess.getComponentDeclAccess().getAlternatives_0(), "rule__ComponentDecl__Alternatives_0");
					put(grammarAccess.getMemberDeclAccess().getAlternatives(), "rule__MemberDecl__Alternatives");
					put(grammarAccess.getAttrDeclAccess().getAlternatives_2(), "rule__AttrDecl__Alternatives_2");
					put(grammarAccess.getModifierAccess().getAlternatives(), "rule__Modifier__Alternatives");
					put(grammarAccess.getSubMemberDeclAccess().getAlternatives_1(), "rule__SubMemberDecl__Alternatives_1");
					put(grammarAccess.getFeatureTypeAccess().getAlternatives(), "rule__FeatureType__Alternatives");
					put(grammarAccess.getInvariantDeclAccess().getAlternatives(), "rule__InvariantDecl__Alternatives");
					put(grammarAccess.getSubMemberMatchAccess().getAlternatives_1(), "rule__SubMemberMatch__Alternatives_1");
					put(grammarAccess.getConstraintNatAccess().getAlternatives(), "rule__ConstraintNat__Alternatives");
					put(grammarAccess.getAttrOrSubMemberAccess().getAlternatives(), "rule__AttrOrSubMember__Alternatives");
					put(grammarAccess.getExpAccess().getAlternatives(), "rule__Exp__Alternatives");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getBinaryOpAccess().getAlternatives(), "rule__BinaryOp__Alternatives");
					put(grammarAccess.getUnaryOpAccess().getAlternatives(), "rule__UnaryOp__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getBaseTypeAccess().getAlternatives(), "rule__BaseType__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getOptionLiteralAccess().getAlternatives(), "rule__OptionLiteral__Alternatives");
					put(grammarAccess.getSimpleLiteralAccess().getAlternatives(), "rule__SimpleLiteral__Alternatives");
					put(grammarAccess.getSimpleOptionLiteralAccess().getAlternatives(), "rule__SimpleOptionLiteral__Alternatives");
					put(grammarAccess.getTypeDeclAccess().getGroup(), "rule__TypeDecl__Group__0");
					put(grammarAccess.getComponentDeclAccess().getGroup(), "rule__ComponentDecl__Group__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_0_0(), "rule__ComponentDecl__Group_0_0__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_0_1(), "rule__ComponentDecl__Group_0_1__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_0_2(), "rule__ComponentDecl__Group_0_2__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_2(), "rule__ComponentDecl__Group_2__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_2_2(), "rule__ComponentDecl__Group_2_2__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_3(), "rule__ComponentDecl__Group_3__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_4(), "rule__ComponentDecl__Group_4__0");
					put(grammarAccess.getComponentDeclAccess().getGroup_5(), "rule__ComponentDecl__Group_5__0");
					put(grammarAccess.getAttrDeclAccess().getGroup(), "rule__AttrDecl__Group__0");
					put(grammarAccess.getAttrDeclAccess().getGroup_2_0(), "rule__AttrDecl__Group_2_0__0");
					put(grammarAccess.getAttrDeclAccess().getGroup_2_0_2(), "rule__AttrDecl__Group_2_0_2__0");
					put(grammarAccess.getAttrDeclAccess().getGroup_2_1(), "rule__AttrDecl__Group_2_1__0");
					put(grammarAccess.getSubMemberDeclAccess().getGroup(), "rule__SubMemberDecl__Group__0");
					put(grammarAccess.getSubMemberDeclAccess().getGroup_1_0(), "rule__SubMemberDecl__Group_1_0__0");
					put(grammarAccess.getSubMemberDeclAccess().getGroup_1_1(), "rule__SubMemberDecl__Group_1_1__0");
					put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
					put(grammarAccess.getReportAccess().getGroup(), "rule__Report__Group__0");
					put(grammarAccess.getReportAccess().getGroup_3(), "rule__Report__Group_3__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_1(), "rule__FeatureType__Group_1__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_2(), "rule__FeatureType__Group_2__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_2_5(), "rule__FeatureType__Group_2_5__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_3(), "rule__FeatureType__Group_3__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_4(), "rule__FeatureType__Group_4__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_4_4(), "rule__FeatureType__Group_4_4__0");
					put(grammarAccess.getFeatureTypeAccess().getGroup_4_6(), "rule__FeatureType__Group_4_6__0");
					put(grammarAccess.getBaseFeatureTypeAccess().getGroup(), "rule__BaseFeatureType__Group__0");
					put(grammarAccess.getBaseFeatureTypeAccess().getGroup_1(), "rule__BaseFeatureType__Group_1__0");
					put(grammarAccess.getBaseFeatureTypeAccess().getGroup_2(), "rule__BaseFeatureType__Group_2__0");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getGroup(), "rule__MultiplicityInvariantDecl__Group__0");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getGroup_1(), "rule__MultiplicityInvariantDecl__Group_1__0");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getGroup_2(), "rule__MultiplicityInvariantDecl__Group_2__0");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getGroup_4(), "rule__MultiplicityInvariantDecl__Group_4__0");
					put(grammarAccess.getGeneralInvariantDeclAccess().getGroup(), "rule__GeneralInvariantDecl__Group__0");
					put(grammarAccess.getGeneralInvariantDeclAccess().getGroup_1(), "rule__GeneralInvariantDecl__Group_1__0");
					put(grammarAccess.getSubMemberMatchAccess().getGroup(), "rule__SubMemberMatch__Group__0");
					put(grammarAccess.getSubMemberMatchAccess().getGroup_0(), "rule__SubMemberMatch__Group_0__0");
					put(grammarAccess.getConstraintNatAccess().getGroup_0(), "rule__ConstraintNat__Group_0__0");
					put(grammarAccess.getConstraintNatAccess().getGroup_1(), "rule__ConstraintNat__Group_1__0");
					put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
					put(grammarAccess.getDeviceAccess().getGroup_3(), "rule__Device__Group_3__0");
					put(grammarAccess.getConstraintExpAccess().getGroup(), "rule__ConstraintExp__Group__0");
					put(grammarAccess.getReportDeclAccess().getGroup(), "rule__ReportDecl__Group__0");
					put(grammarAccess.getReportDeclAccess().getGroup_4(), "rule__ReportDecl__Group_4__0");
					put(grammarAccess.getParamAccess().getGroup(), "rule__Param__Group__0");
					put(grammarAccess.getReportMemberDeclAccess().getGroup(), "rule__ReportMemberDecl__Group__0");
					put(grammarAccess.getReportMemberDeclAccess().getGroup_2(), "rule__ReportMemberDecl__Group_2__0");
					put(grammarAccess.getExpAccess().getGroup_0(), "rule__Exp__Group_0__0");
					put(grammarAccess.getExpAccess().getGroup_1(), "rule__Exp__Group_1__0");
					put(grammarAccess.getExpAccess().getGroup_2(), "rule__Exp__Group_2__0");
					put(grammarAccess.getExpAccess().getGroup_2_2(), "rule__Exp__Group_2_2__0");
					put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getTypeAccess().getGroup_0(), "rule__Type__Group_0__0");
					put(grammarAccess.getTypeAccess().getGroup_1(), "rule__Type__Group_1__0");
					put(grammarAccess.getBaseTypeAccess().getGroup_1(), "rule__BaseType__Group_1__0");
					put(grammarAccess.getBaseTypeAccess().getGroup_1_3(), "rule__BaseType__Group_1_3__0");
					put(grammarAccess.getBaseTypeAccess().getGroup_2(), "rule__BaseType__Group_2__0");
					put(grammarAccess.getBaseTypeAccess().getGroup_3(), "rule__BaseType__Group_3__0");
					put(grammarAccess.getBaseTypeAccess().getGroup_4(), "rule__BaseType__Group_4__0");
					put(grammarAccess.getBasicLiteralAccess().getGroup(), "rule__BasicLiteral__Group__0");
					put(grammarAccess.getTupleLiteralAccess().getGroup(), "rule__TupleLiteral__Group__0");
					put(grammarAccess.getTupleLiteralAccess().getGroup_2(), "rule__TupleLiteral__Group_2__0");
					put(grammarAccess.getTupleLiteralAccess().getGroup_2_1(), "rule__TupleLiteral__Group_2_1__0");
					put(grammarAccess.getSeqLiteralAccess().getGroup(), "rule__SeqLiteral__Group__0");
					put(grammarAccess.getSeqLiteralAccess().getGroup_3(), "rule__SeqLiteral__Group_3__0");
					put(grammarAccess.getSeqLiteralAccess().getGroup_3_1(), "rule__SeqLiteral__Group_3_1__0");
					put(grammarAccess.getSetLiteralAccess().getGroup(), "rule__SetLiteral__Group__0");
					put(grammarAccess.getSetLiteralAccess().getGroup_3(), "rule__SetLiteral__Group_3__0");
					put(grammarAccess.getSetLiteralAccess().getGroup_3_1(), "rule__SetLiteral__Group_3_1__0");
					put(grammarAccess.getOptionLiteralAccess().getGroup_0(), "rule__OptionLiteral__Group_0__0");
					put(grammarAccess.getOptionLiteralAccess().getGroup_1(), "rule__OptionLiteral__Group_1__0");
					put(grammarAccess.getSimpleTupleLiteralAccess().getGroup(), "rule__SimpleTupleLiteral__Group__0");
					put(grammarAccess.getSimpleTupleLiteralAccess().getGroup_2(), "rule__SimpleTupleLiteral__Group_2__0");
					put(grammarAccess.getSimpleTupleLiteralAccess().getGroup_2_1(), "rule__SimpleTupleLiteral__Group_2_1__0");
					put(grammarAccess.getSimpleOptionLiteralAccess().getGroup_0(), "rule__SimpleOptionLiteral__Group_0__0");
					put(grammarAccess.getSimpleOptionLiteralAccess().getGroup_1(), "rule__SimpleOptionLiteral__Group_1__0");
					put(grammarAccess.getSimpleSeqLiteralAccess().getGroup(), "rule__SimpleSeqLiteral__Group__0");
					put(grammarAccess.getSimpleSeqLiteralAccess().getGroup_2(), "rule__SimpleSeqLiteral__Group_2__0");
					put(grammarAccess.getSimpleSeqLiteralAccess().getGroup_2_1(), "rule__SimpleSeqLiteral__Group_2_1__0");
					put(grammarAccess.getSimpleSetLiteralAccess().getGroup(), "rule__SimpleSetLiteral__Group__0");
					put(grammarAccess.getSimpleSetLiteralAccess().getGroup_2(), "rule__SimpleSetLiteral__Group_2__0");
					put(grammarAccess.getSimpleSetLiteralAccess().getGroup_2_1(), "rule__SimpleSetLiteral__Group_2_1__0");
					put(grammarAccess.getModelAccess().getDeclsAssignment(), "rule__Model__DeclsAssignment");
					put(grammarAccess.getTypeDeclAccess().getNameAssignment_1(), "rule__TypeDecl__NameAssignment_1");
					put(grammarAccess.getComponentDeclAccess().getNameAssignment_1(), "rule__ComponentDecl__NameAssignment_1");
					put(grammarAccess.getComponentDeclAccess().getSupersAssignment_2_1(), "rule__ComponentDecl__SupersAssignment_2_1");
					put(grammarAccess.getComponentDeclAccess().getSupersAssignment_2_2_1(), "rule__ComponentDecl__SupersAssignment_2_2_1");
					put(grammarAccess.getComponentDeclAccess().getMembersAssignment_3_1(), "rule__ComponentDecl__MembersAssignment_3_1");
					put(grammarAccess.getComponentDeclAccess().getDevicesAssignment_4_2(), "rule__ComponentDecl__DevicesAssignment_4_2");
					put(grammarAccess.getComponentDeclAccess().getAssignsAssignment_4_3(), "rule__ComponentDecl__AssignsAssignment_4_3");
					put(grammarAccess.getComponentDeclAccess().getExpAssignment_4_4(), "rule__ComponentDecl__ExpAssignment_4_4");
					put(grammarAccess.getComponentDeclAccess().getReportsAssignment_5_2(), "rule__ComponentDecl__ReportsAssignment_5_2");
					put(grammarAccess.getAttrDeclAccess().getModifierAssignment_0(), "rule__AttrDecl__ModifierAssignment_0");
					put(grammarAccess.getAttrDeclAccess().getAttributeNameAssignment_1(), "rule__AttrDecl__AttributeNameAssignment_1");
					put(grammarAccess.getAttrDeclAccess().getTypeAssignment_2_0_1(), "rule__AttrDecl__TypeAssignment_2_0_1");
					put(grammarAccess.getAttrDeclAccess().getLiteralAssignment_2_0_2_1(), "rule__AttrDecl__LiteralAssignment_2_0_2_1");
					put(grammarAccess.getAttrDeclAccess().getLiteralAssignment_2_1_1(), "rule__AttrDecl__LiteralAssignment_2_1_1");
					put(grammarAccess.getSubMemberDeclAccess().getNameAssignment_0(), "rule__SubMemberDecl__NameAssignment_0");
					put(grammarAccess.getSubMemberDeclAccess().getTypeAssignment_1_0_1(), "rule__SubMemberDecl__TypeAssignment_1_0_1");
					put(grammarAccess.getSubMemberDeclAccess().getMembersAssignment_1_1_2(), "rule__SubMemberDecl__MembersAssignment_1_1_2");
					put(grammarAccess.getAssignmentAccess().getNameAssignment_0(), "rule__Assignment__NameAssignment_0");
					put(grammarAccess.getAssignmentAccess().getExpAssignment_2(), "rule__Assignment__ExpAssignment_2");
					put(grammarAccess.getReportAccess().getNameAssignment_0(), "rule__Report__NameAssignment_0");
					put(grammarAccess.getReportAccess().getArgsAssignment_2(), "rule__Report__ArgsAssignment_2");
					put(grammarAccess.getReportAccess().getArgsAssignment_3_1(), "rule__Report__ArgsAssignment_3_1");
					put(grammarAccess.getFeatureTypeAccess().getBaseAssignment_1_3(), "rule__FeatureType__BaseAssignment_1_3");
					put(grammarAccess.getFeatureTypeAccess().getBaseAssignment_2_3(), "rule__FeatureType__BaseAssignment_2_3");
					put(grammarAccess.getFeatureTypeAccess().getMembersAssignment_2_5_2(), "rule__FeatureType__MembersAssignment_2_5_2");
					put(grammarAccess.getFeatureTypeAccess().getBaseAssignment_3_3(), "rule__FeatureType__BaseAssignment_3_3");
					put(grammarAccess.getFeatureTypeAccess().getBasesAssignment_4_3(), "rule__FeatureType__BasesAssignment_4_3");
					put(grammarAccess.getFeatureTypeAccess().getBasesAssignment_4_4_1(), "rule__FeatureType__BasesAssignment_4_4_1");
					put(grammarAccess.getFeatureTypeAccess().getChoiceAssignment_4_6_1(), "rule__FeatureType__ChoiceAssignment_4_6_1");
					put(grammarAccess.getFeatureTypeAccess().getMembersAssignment_4_6_3(), "rule__FeatureType__MembersAssignment_4_6_3");
					put(grammarAccess.getBaseFeatureTypeAccess().getComponentsAssignment_0(), "rule__BaseFeatureType__ComponentsAssignment_0");
					put(grammarAccess.getBaseFeatureTypeAccess().getComponentsAssignment_1_1(), "rule__BaseFeatureType__ComponentsAssignment_1_1");
					put(grammarAccess.getBaseFeatureTypeAccess().getMembersAssignment_2_2(), "rule__BaseFeatureType__MembersAssignment_2_2");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getInvNameAssignment_1_0(), "rule__MultiplicityInvariantDecl__InvNameAssignment_1_0");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getLoAssignment_2_0(), "rule__MultiplicityInvariantDecl__LoAssignment_2_0");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getHiAssignment_2_2(), "rule__MultiplicityInvariantDecl__HiAssignment_2_2");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getMatchAssignment_3(), "rule__MultiplicityInvariantDecl__MatchAssignment_3");
					put(grammarAccess.getMultiplicityInvariantDeclAccess().getTypeAssignment_4_1(), "rule__MultiplicityInvariantDecl__TypeAssignment_4_1");
					put(grammarAccess.getGeneralInvariantDeclAccess().getInvNameAssignment_1_0(), "rule__GeneralInvariantDecl__InvNameAssignment_1_0");
					put(grammarAccess.getGeneralInvariantDeclAccess().getExpAssignment_2(), "rule__GeneralInvariantDecl__ExpAssignment_2");
					put(grammarAccess.getSubMemberMatchAccess().getQNamesAssignment_0_0(), "rule__SubMemberMatch__QNamesAssignment_0_0");
					put(grammarAccess.getSubMemberMatchAccess().getNameAssignment_1_0(), "rule__SubMemberMatch__NameAssignment_1_0");
					put(grammarAccess.getSubMemberMatchAccess().getAnyAssignment_1_1(), "rule__SubMemberMatch__AnyAssignment_1_1");
					put(grammarAccess.getConstraintNatAccess().getNumAssignment_0_1(), "rule__ConstraintNat__NumAssignment_0_1");
					put(grammarAccess.getDeviceAccess().getNameAssignment_0(), "rule__Device__NameAssignment_0");
					put(grammarAccess.getDeviceAccess().getComponentsAssignment_2(), "rule__Device__ComponentsAssignment_2");
					put(grammarAccess.getDeviceAccess().getComponentsAssignment_3_1(), "rule__Device__ComponentsAssignment_3_1");
					put(grammarAccess.getDeviceAccess().getConstraintAssignment_4(), "rule__Device__ConstraintAssignment_4");
					put(grammarAccess.getReportDeclAccess().getNameAssignment_1(), "rule__ReportDecl__NameAssignment_1");
					put(grammarAccess.getReportDeclAccess().getParamsAssignment_3(), "rule__ReportDecl__ParamsAssignment_3");
					put(grammarAccess.getReportDeclAccess().getParamsAssignment_4_1(), "rule__ReportDecl__ParamsAssignment_4_1");
					put(grammarAccess.getReportDeclAccess().getAttrsAssignment_7(), "rule__ReportDecl__AttrsAssignment_7");
					put(grammarAccess.getParamAccess().getNameAssignment_0(), "rule__Param__NameAssignment_0");
					put(grammarAccess.getParamAccess().getTypeAssignment_2(), "rule__Param__TypeAssignment_2");
					put(grammarAccess.getReportMemberDeclAccess().getNameAssignment_0(), "rule__ReportMemberDecl__NameAssignment_0");
					put(grammarAccess.getReportMemberDeclAccess().getBindingNameAssignment_2_0(), "rule__ReportMemberDecl__BindingNameAssignment_2_0");
					put(grammarAccess.getReportMemberDeclAccess().getBindingNameAssignment_3(), "rule__ReportMemberDecl__BindingNameAssignment_3");
					put(grammarAccess.getExpAccess().getLeftAssignment_0_2(), "rule__Exp__LeftAssignment_0_2");
					put(grammarAccess.getExpAccess().getOpAssignment_0_3(), "rule__Exp__OpAssignment_0_3");
					put(grammarAccess.getExpAccess().getRightAssignment_0_4(), "rule__Exp__RightAssignment_0_4");
					put(grammarAccess.getExpAccess().getOpAssignment_1_2(), "rule__Exp__OpAssignment_1_2");
					put(grammarAccess.getExpAccess().getArgAssignment_1_3(), "rule__Exp__ArgAssignment_1_3");
					put(grammarAccess.getExpAccess().getPrimaryAssignment_2_1(), "rule__Exp__PrimaryAssignment_2_1");
					put(grammarAccess.getExpAccess().getNameAssignment_2_2_2(), "rule__Exp__NameAssignment_2_2_2");
					put(grammarAccess.getPrimaryAccess().getIdAssignment_0_1(), "rule__Primary__IdAssignment_0_1");
					put(grammarAccess.getPrimaryAccess().getLitAssignment_1_1(), "rule__Primary__LitAssignment_1_1");
					put(grammarAccess.getTypeAccess().getBaseAssignment_0_3(), "rule__Type__BaseAssignment_0_3");
					put(grammarAccess.getTypeAccess().getBaseAssignment_1_3(), "rule__Type__BaseAssignment_1_3");
					put(grammarAccess.getBaseTypeAccess().getTypeAssignment_0(), "rule__BaseType__TypeAssignment_0");
					put(grammarAccess.getBaseTypeAccess().getElemTypesAssignment_1_2(), "rule__BaseType__ElemTypesAssignment_1_2");
					put(grammarAccess.getBaseTypeAccess().getElemTypesAssignment_1_3_1(), "rule__BaseType__ElemTypesAssignment_1_3_1");
					put(grammarAccess.getBaseTypeAccess().getBaseAssignment_2_3(), "rule__BaseType__BaseAssignment_2_3");
					put(grammarAccess.getBaseTypeAccess().getBaseAssignment_3_3(), "rule__BaseType__BaseAssignment_3_3");
					put(grammarAccess.getBaseTypeAccess().getBaseAssignment_4_3(), "rule__BaseType__BaseAssignment_4_3");
					put(grammarAccess.getBasicLiteralAccess().getTypeConsAssignment_0(), "rule__BasicLiteral__TypeConsAssignment_0");
					put(grammarAccess.getBasicLiteralAccess().getLitAssignment_1(), "rule__BasicLiteral__LitAssignment_1");
					put(grammarAccess.getTupleLiteralAccess().getElemsAssignment_2_0(), "rule__TupleLiteral__ElemsAssignment_2_0");
					put(grammarAccess.getTupleLiteralAccess().getElemsAssignment_2_1_1(), "rule__TupleLiteral__ElemsAssignment_2_1_1");
					put(grammarAccess.getSeqLiteralAccess().getBasicTypeAssignment_1(), "rule__SeqLiteral__BasicTypeAssignment_1");
					put(grammarAccess.getSeqLiteralAccess().getElemsAssignment_3_0(), "rule__SeqLiteral__ElemsAssignment_3_0");
					put(grammarAccess.getSeqLiteralAccess().getElemsAssignment_3_1_1(), "rule__SeqLiteral__ElemsAssignment_3_1_1");
					put(grammarAccess.getSetLiteralAccess().getBasicTypeAssignment_1(), "rule__SetLiteral__BasicTypeAssignment_1");
					put(grammarAccess.getSetLiteralAccess().getElemsAssignment_3_0(), "rule__SetLiteral__ElemsAssignment_3_0");
					put(grammarAccess.getSetLiteralAccess().getElemsAssignment_3_1_1(), "rule__SetLiteral__ElemsAssignment_3_1_1");
					put(grammarAccess.getOptionLiteralAccess().getTypeAssignment_0_3(), "rule__OptionLiteral__TypeAssignment_0_3");
					put(grammarAccess.getOptionLiteralAccess().getLitAssignment_1_2(), "rule__OptionLiteral__LitAssignment_1_2");
					put(grammarAccess.getSimpleBasicLiteralAccess().getLitAssignment(), "rule__SimpleBasicLiteral__LitAssignment");
					put(grammarAccess.getSimpleTupleLiteralAccess().getElemsAssignment_2_0(), "rule__SimpleTupleLiteral__ElemsAssignment_2_0");
					put(grammarAccess.getSimpleTupleLiteralAccess().getElemsAssignment_2_1_1(), "rule__SimpleTupleLiteral__ElemsAssignment_2_1_1");
					put(grammarAccess.getSimpleOptionLiteralAccess().getLitAssignment_1_2(), "rule__SimpleOptionLiteral__LitAssignment_1_2");
					put(grammarAccess.getSimpleSeqLiteralAccess().getElemsAssignment_2_0(), "rule__SimpleSeqLiteral__ElemsAssignment_2_0");
					put(grammarAccess.getSimpleSeqLiteralAccess().getElemsAssignment_2_1_1(), "rule__SimpleSeqLiteral__ElemsAssignment_2_1_1");
					put(grammarAccess.getSimpleSetLiteralAccess().getElemsAssignment_2_0(), "rule__SimpleSetLiteral__ElemsAssignment_2_0");
					put(grammarAccess.getSimpleSetLiteralAccess().getElemsAssignment_2_1_1(), "rule__SimpleSetLiteral__ElemsAssignment_2_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			edu.ksu.cis.projects.mdcf.devicemodel.ui.contentassist.antlr.internal.InternalDeviceModelingLanguageParser typedParser = (edu.ksu.cis.projects.mdcf.devicemodel.ui.contentassist.antlr.internal.InternalDeviceModelingLanguageParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DeviceModelingLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DeviceModelingLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
