/*
* generated by Xtext
*/

package edu.ksu.cis.projects.mdcf.devicemodel.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class DeviceModelingLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cDeclsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDeclsDeclParserRuleCall_0 = (RuleCall)cDeclsAssignment.eContents().get(0);
		
		//Model:
		//	decls+=Decl*;
		public ParserRule getRule() { return rule; }

		//decls+=Decl*
		public Assignment getDeclsAssignment() { return cDeclsAssignment; }

		//Decl
		public RuleCall getDeclsDeclParserRuleCall_0() { return cDeclsDeclParserRuleCall_0; }
	}

	public class DeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Decl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTypeDeclParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFeaturesDeclParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Decl:
		//	TypeDecl | FeaturesDecl;
		public ParserRule getRule() { return rule; }

		//TypeDecl | FeaturesDecl
		public Alternatives getAlternatives() { return cAlternatives; }

		//TypeDecl
		public RuleCall getTypeDeclParserRuleCall_0() { return cTypeDeclParserRuleCall_0; }

		//FeaturesDecl
		public RuleCall getFeaturesDeclParserRuleCall_1() { return cFeaturesDeclParserRuleCall_1; }
	}

	public class TypeDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TypeDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLessThanSignColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSupersAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSupersTypeDeclCrossReference_2_1_0 = (CrossReference)cSupersAssignment_2_1.eContents().get(0);
		private final RuleCall cSupersTypeDeclIDTerminalRuleCall_2_1_0_1 = (RuleCall)cSupersTypeDeclCrossReference_2_1_0.eContents().get(1);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cSupersAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final CrossReference cSupersTypeDeclCrossReference_2_2_1_0 = (CrossReference)cSupersAssignment_2_2_1.eContents().get(0);
		private final RuleCall cSupersTypeDeclIDTerminalRuleCall_2_2_1_0_1 = (RuleCall)cSupersTypeDeclCrossReference_2_2_1_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Assignment cElemsAssignment_3_1_0 = (Assignment)cGroup_3_1.eContents().get(0);
		private final RuleCall cElemsELiteralParserRuleCall_3_1_0_0 = (RuleCall)cElemsAssignment_3_1_0.eContents().get(0);
		private final Group cGroup_3_1_1 = (Group)cGroup_3_1.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_1_0 = (Keyword)cGroup_3_1_1.eContents().get(0);
		private final Assignment cElemsAssignment_3_1_1_1 = (Assignment)cGroup_3_1_1.eContents().get(1);
		private final RuleCall cElemsELiteralParserRuleCall_3_1_1_1_0 = (RuleCall)cElemsAssignment_3_1_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//TypeDecl:
		//	"type" name=ID ("<:" supers+=[TypeDecl] ("," supers+=[TypeDecl])*)? ("{" (elems+=ELiteral ("," elems+=ELiteral)*)?
		//	"}")?;
		public ParserRule getRule() { return rule; }

		//"type" name=ID ("<:" supers+=[TypeDecl] ("," supers+=[TypeDecl])*)? ("{" (elems+=ELiteral ("," elems+=ELiteral)*)? "}")?
		public Group getGroup() { return cGroup; }

		//"type"
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("<:" supers+=[TypeDecl] ("," supers+=[TypeDecl])*)?
		public Group getGroup_2() { return cGroup_2; }

		//"<:"
		public Keyword getLessThanSignColonKeyword_2_0() { return cLessThanSignColonKeyword_2_0; }

		//supers+=[TypeDecl]
		public Assignment getSupersAssignment_2_1() { return cSupersAssignment_2_1; }

		//[TypeDecl]
		public CrossReference getSupersTypeDeclCrossReference_2_1_0() { return cSupersTypeDeclCrossReference_2_1_0; }

		//ID
		public RuleCall getSupersTypeDeclIDTerminalRuleCall_2_1_0_1() { return cSupersTypeDeclIDTerminalRuleCall_2_1_0_1; }

		//("," supers+=[TypeDecl])*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//supers+=[TypeDecl]
		public Assignment getSupersAssignment_2_2_1() { return cSupersAssignment_2_2_1; }

		//[TypeDecl]
		public CrossReference getSupersTypeDeclCrossReference_2_2_1_0() { return cSupersTypeDeclCrossReference_2_2_1_0; }

		//ID
		public RuleCall getSupersTypeDeclIDTerminalRuleCall_2_2_1_0_1() { return cSupersTypeDeclIDTerminalRuleCall_2_2_1_0_1; }

		//("{" (elems+=ELiteral ("," elems+=ELiteral)*)? "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_0() { return cLeftCurlyBracketKeyword_3_0; }

		//(elems+=ELiteral ("," elems+=ELiteral)*)?
		public Group getGroup_3_1() { return cGroup_3_1; }

		//elems+=ELiteral
		public Assignment getElemsAssignment_3_1_0() { return cElemsAssignment_3_1_0; }

		//ELiteral
		public RuleCall getElemsELiteralParserRuleCall_3_1_0_0() { return cElemsELiteralParserRuleCall_3_1_0_0; }

		//("," elems+=ELiteral)*
		public Group getGroup_3_1_1() { return cGroup_3_1_1; }

		//","
		public Keyword getCommaKeyword_3_1_1_0() { return cCommaKeyword_3_1_1_0; }

		//elems+=ELiteral
		public Assignment getElemsAssignment_3_1_1_1() { return cElemsAssignment_3_1_1_1; }

		//ELiteral
		public RuleCall getElemsELiteralParserRuleCall_3_1_1_1_0() { return cElemsELiteralParserRuleCall_3_1_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_2() { return cRightCurlyBracketKeyword_3_2; }
	}

	public class FeaturesDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FeaturesDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCompleteAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cCompleteCompleteKeyword_0_0 = (Keyword)cCompleteAssignment_0.eContents().get(0);
		private final Keyword cFeaturesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLessThanSignColonKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSupersAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cSupersFeaturesDeclCrossReference_3_1_0 = (CrossReference)cSupersAssignment_3_1.eContents().get(0);
		private final RuleCall cSupersFeaturesDeclIDTerminalRuleCall_3_1_0_1 = (RuleCall)cSupersFeaturesDeclCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cSupersAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final CrossReference cSupersFeaturesDeclCrossReference_3_2_1_0 = (CrossReference)cSupersAssignment_3_2_1.eContents().get(0);
		private final RuleCall cSupersFeaturesDeclIDTerminalRuleCall_3_2_1_0_1 = (RuleCall)cSupersFeaturesDeclCrossReference_3_2_1_0.eContents().get(1);
		private final Assignment cBodyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBodyFeaturesBodyParserRuleCall_4_0 = (RuleCall)cBodyAssignment_4.eContents().get(0);
		
		//FeaturesDecl:
		//	complete="complete"? "features" name=ID ("<:" supers+=[FeaturesDecl] ("," supers+=[FeaturesDecl])*)?
		//	body=FeaturesBody;
		public ParserRule getRule() { return rule; }

		//complete="complete"? "features" name=ID ("<:" supers+=[FeaturesDecl] ("," supers+=[FeaturesDecl])*)? body=FeaturesBody
		public Group getGroup() { return cGroup; }

		//complete="complete"?
		public Assignment getCompleteAssignment_0() { return cCompleteAssignment_0; }

		//"complete"
		public Keyword getCompleteCompleteKeyword_0_0() { return cCompleteCompleteKeyword_0_0; }

		//"features"
		public Keyword getFeaturesKeyword_1() { return cFeaturesKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//("<:" supers+=[FeaturesDecl] ("," supers+=[FeaturesDecl])*)?
		public Group getGroup_3() { return cGroup_3; }

		//"<:"
		public Keyword getLessThanSignColonKeyword_3_0() { return cLessThanSignColonKeyword_3_0; }

		//supers+=[FeaturesDecl]
		public Assignment getSupersAssignment_3_1() { return cSupersAssignment_3_1; }

		//[FeaturesDecl]
		public CrossReference getSupersFeaturesDeclCrossReference_3_1_0() { return cSupersFeaturesDeclCrossReference_3_1_0; }

		//ID
		public RuleCall getSupersFeaturesDeclIDTerminalRuleCall_3_1_0_1() { return cSupersFeaturesDeclIDTerminalRuleCall_3_1_0_1; }

		//("," supers+=[FeaturesDecl])*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//supers+=[FeaturesDecl]
		public Assignment getSupersAssignment_3_2_1() { return cSupersAssignment_3_2_1; }

		//[FeaturesDecl]
		public CrossReference getSupersFeaturesDeclCrossReference_3_2_1_0() { return cSupersFeaturesDeclCrossReference_3_2_1_0; }

		//ID
		public RuleCall getSupersFeaturesDeclIDTerminalRuleCall_3_2_1_0_1() { return cSupersFeaturesDeclIDTerminalRuleCall_3_2_1_0_1; }

		//body=FeaturesBody
		public Assignment getBodyAssignment_4() { return cBodyAssignment_4; }

		//FeaturesBody
		public RuleCall getBodyFeaturesBodyParserRuleCall_4_0() { return cBodyFeaturesBodyParserRuleCall_4_0; }
	}

	public class FeaturesBodyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FeaturesBody");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Action cFeaturesBodyAction_1 = (Action)cGroup.eContents().get(1);
		private final Assignment cFeaturesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFeaturesFeatureDeclParserRuleCall_2_0 = (RuleCall)cFeaturesAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FeaturesBody:
		//	"{" {FeaturesBody} features+=FeatureDecl* "}";
		public ParserRule getRule() { return rule; }

		//"{" {FeaturesBody} features+=FeatureDecl* "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//{FeaturesBody}
		public Action getFeaturesBodyAction_1() { return cFeaturesBodyAction_1; }

		//features+=FeatureDecl*
		public Assignment getFeaturesAssignment_2() { return cFeaturesAssignment_2; }

		//FeatureDecl
		public RuleCall getFeaturesFeatureDeclParserRuleCall_2_0() { return cFeaturesFeatureDeclParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class FeatureDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FeatureDecl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInvariantDeclParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAttrDeclParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSubFeaturesDeclParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//FeatureDecl:
		//	InvariantDecl | AttrDecl | SubFeaturesDecl;
		public ParserRule getRule() { return rule; }

		//InvariantDecl | AttrDecl | SubFeaturesDecl
		public Alternatives getAlternatives() { return cAlternatives; }

		//InvariantDecl
		public RuleCall getInvariantDeclParserRuleCall_0() { return cInvariantDeclParserRuleCall_0; }

		//AttrDecl
		public RuleCall getAttrDeclParserRuleCall_1() { return cAttrDeclParserRuleCall_1; }

		//SubFeaturesDecl
		public RuleCall getSubFeaturesDeclParserRuleCall_2() { return cSubFeaturesDeclParserRuleCall_2; }
	}

	public class InvariantDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InvariantDecl");
		private final RuleCall cMultiplicityInvariantDeclParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//InvariantDecl:
		//	MultiplicityInvariantDecl;
		public ParserRule getRule() { return rule; }

		//MultiplicityInvariantDecl
		public RuleCall getMultiplicityInvariantDeclParserRuleCall() { return cMultiplicityInvariantDeclParserRuleCall; }
	}

	public class MultiplicityInvariantDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultiplicityInvariantDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInvKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cInvNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cInvNameIDTerminalRuleCall_1_0_0 = (RuleCall)cInvNameAssignment_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cLoAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cLoConstraintNatParserRuleCall_2_0_0 = (RuleCall)cLoAssignment_2_0.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cHiAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cHiConstraintNatParserRuleCall_2_2_0 = (RuleCall)cHiAssignment_2_2.eContents().get(0);
		private final Assignment cMatchAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMatchSubFeaturesMatchParserRuleCall_3_0 = (RuleCall)cMatchAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTypeFeaturesDeclCrossReference_4_1_0 = (CrossReference)cTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cTypeFeaturesDeclIDTerminalRuleCall_4_1_0_1 = (RuleCall)cTypeFeaturesDeclCrossReference_4_1_0.eContents().get(1);
		
		//MultiplicityInvariantDecl:
		//	"inv" (invName=ID ":")? (lo=ConstraintNat ".." hi=ConstraintNat) match=SubFeaturesMatch (":" type=[FeaturesDecl])?;
		public ParserRule getRule() { return rule; }

		//"inv" (invName=ID ":")? (lo=ConstraintNat ".." hi=ConstraintNat) match=SubFeaturesMatch (":" type=[FeaturesDecl])?
		public Group getGroup() { return cGroup; }

		//"inv"
		public Keyword getInvKeyword_0() { return cInvKeyword_0; }

		//(invName=ID ":")?
		public Group getGroup_1() { return cGroup_1; }

		//invName=ID
		public Assignment getInvNameAssignment_1_0() { return cInvNameAssignment_1_0; }

		//ID
		public RuleCall getInvNameIDTerminalRuleCall_1_0_0() { return cInvNameIDTerminalRuleCall_1_0_0; }

		//":"
		public Keyword getColonKeyword_1_1() { return cColonKeyword_1_1; }

		//lo=ConstraintNat ".." hi=ConstraintNat
		public Group getGroup_2() { return cGroup_2; }

		//lo=ConstraintNat
		public Assignment getLoAssignment_2_0() { return cLoAssignment_2_0; }

		//ConstraintNat
		public RuleCall getLoConstraintNatParserRuleCall_2_0_0() { return cLoConstraintNatParserRuleCall_2_0_0; }

		//".."
		public Keyword getFullStopFullStopKeyword_2_1() { return cFullStopFullStopKeyword_2_1; }

		//hi=ConstraintNat
		public Assignment getHiAssignment_2_2() { return cHiAssignment_2_2; }

		//ConstraintNat
		public RuleCall getHiConstraintNatParserRuleCall_2_2_0() { return cHiConstraintNatParserRuleCall_2_2_0; }

		//match=SubFeaturesMatch
		public Assignment getMatchAssignment_3() { return cMatchAssignment_3; }

		//SubFeaturesMatch
		public RuleCall getMatchSubFeaturesMatchParserRuleCall_3_0() { return cMatchSubFeaturesMatchParserRuleCall_3_0; }

		//(":" type=[FeaturesDecl])?
		public Group getGroup_4() { return cGroup_4; }

		//":"
		public Keyword getColonKeyword_4_0() { return cColonKeyword_4_0; }

		//type=[FeaturesDecl]
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }

		//[FeaturesDecl]
		public CrossReference getTypeFeaturesDeclCrossReference_4_1_0() { return cTypeFeaturesDeclCrossReference_4_1_0; }

		//ID
		public RuleCall getTypeFeaturesDeclIDTerminalRuleCall_4_1_0_1() { return cTypeFeaturesDeclIDTerminalRuleCall_4_1_0_1; }
	}

	public class SubFeaturesMatchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SubFeaturesMatch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSubFeaturesMatchAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cCategoryNamesAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cCategoryNamesIDTerminalRuleCall_1_0_0 = (RuleCall)cCategoryNamesAssignment_1_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_2_0_0 = (RuleCall)cNameAssignment_2_0.eContents().get(0);
		private final Assignment cAnyAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final Keyword cAnyAsteriskKeyword_2_1_0 = (Keyword)cAnyAssignment_2_1.eContents().get(0);
		
		//SubFeaturesMatch:
		//	{SubFeaturesMatch} (categoryNames+=ID ".")* (name=ID | any="*");
		public ParserRule getRule() { return rule; }

		//{SubFeaturesMatch} (categoryNames+=ID ".")* (name=ID | any="*")
		public Group getGroup() { return cGroup; }

		//{SubFeaturesMatch}
		public Action getSubFeaturesMatchAction_0() { return cSubFeaturesMatchAction_0; }

		//(categoryNames+=ID ".")*
		public Group getGroup_1() { return cGroup_1; }

		//categoryNames+=ID
		public Assignment getCategoryNamesAssignment_1_0() { return cCategoryNamesAssignment_1_0; }

		//ID
		public RuleCall getCategoryNamesIDTerminalRuleCall_1_0_0() { return cCategoryNamesIDTerminalRuleCall_1_0_0; }

		//"."
		public Keyword getFullStopKeyword_1_1() { return cFullStopKeyword_1_1; }

		//name=ID | any="*"
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//name=ID
		public Assignment getNameAssignment_2_0() { return cNameAssignment_2_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_0() { return cNameIDTerminalRuleCall_2_0_0; }

		//any="*"
		public Assignment getAnyAssignment_2_1() { return cAnyAssignment_2_1; }

		//"*"
		public Keyword getAnyAsteriskKeyword_2_1_0() { return cAnyAsteriskKeyword_2_1_0; }
	}

	public class ConstraintNatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConstraintNat");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cNumNatConstraintAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cNumAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNumNATTerminalRuleCall_0_1_0 = (RuleCall)cNumAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cAnyNatConstraintAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//ConstraintNat:
		//	{NumNatConstraint} num=NAT | {AnyNatConstraint} "*";
		public ParserRule getRule() { return rule; }

		//{NumNatConstraint} num=NAT | {AnyNatConstraint} "*"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{NumNatConstraint} num=NAT
		public Group getGroup_0() { return cGroup_0; }

		//{NumNatConstraint}
		public Action getNumNatConstraintAction_0_0() { return cNumNatConstraintAction_0_0; }

		//num=NAT
		public Assignment getNumAssignment_0_1() { return cNumAssignment_0_1; }

		//NAT
		public RuleCall getNumNATTerminalRuleCall_0_1_0() { return cNumNATTerminalRuleCall_0_1_0; }

		//{AnyNatConstraint} "*"
		public Group getGroup_1() { return cGroup_1; }

		//{AnyNatConstraint}
		public Action getAnyNatConstraintAction_1_0() { return cAnyNatConstraintAction_1_0; }

		//"*"
		public Keyword getAsteriskKeyword_1_1() { return cAsteriskKeyword_1_1; }
	}

	public class AttrDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AttrDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cModifierAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cModifierModifierParserRuleCall_0_0 = (RuleCall)cModifierAssignment_0.eContents().get(0);
		private final Assignment cAttributeNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAttributeNameIDTerminalRuleCall_1_0 = (RuleCall)cAttributeNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cColonKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cTypeAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_2_0_1_0 = (RuleCall)cTypeAssignment_2_0_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cLiteralAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cLiteralLiteralParserRuleCall_2_1_1_0 = (RuleCall)cLiteralAssignment_2_1_1.eContents().get(0);
		
		//AttrDecl:
		//	modifier=Modifier attributeName=ID (":" type=Type | "=" literal=Literal);
		public ParserRule getRule() { return rule; }

		//modifier=Modifier attributeName=ID (":" type=Type | "=" literal=Literal)
		public Group getGroup() { return cGroup; }

		//modifier=Modifier
		public Assignment getModifierAssignment_0() { return cModifierAssignment_0; }

		//Modifier
		public RuleCall getModifierModifierParserRuleCall_0_0() { return cModifierModifierParserRuleCall_0_0; }

		//attributeName=ID
		public Assignment getAttributeNameAssignment_1() { return cAttributeNameAssignment_1; }

		//ID
		public RuleCall getAttributeNameIDTerminalRuleCall_1_0() { return cAttributeNameIDTerminalRuleCall_1_0; }

		//":" type=Type | "=" literal=Literal
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//":" type=Type
		public Group getGroup_2_0() { return cGroup_2_0; }

		//":"
		public Keyword getColonKeyword_2_0_0() { return cColonKeyword_2_0_0; }

		//type=Type
		public Assignment getTypeAssignment_2_0_1() { return cTypeAssignment_2_0_1; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_2_0_1_0() { return cTypeTypeParserRuleCall_2_0_1_0; }

		//"=" literal=Literal
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"="
		public Keyword getEqualsSignKeyword_2_1_0() { return cEqualsSignKeyword_2_1_0; }

		//literal=Literal
		public Assignment getLiteralAssignment_2_1_1() { return cLiteralAssignment_2_1_1; }

		//Literal
		public RuleCall getLiteralLiteralParserRuleCall_2_1_1_0() { return cLiteralLiteralParserRuleCall_2_1_1_0; }
	}

	public class ModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Modifier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cConstKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cValKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cVarKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cDefKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//Modifier:
		//	"const" | "val" | "var" | "def";
		public ParserRule getRule() { return rule; }

		//"const" | "val" | "var" | "def"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"const"
		public Keyword getConstKeyword_0() { return cConstKeyword_0; }

		//"val"
		public Keyword getValKeyword_1() { return cValKeyword_1; }

		//"var"
		public Keyword getVarKeyword_2() { return cVarKeyword_2; }

		//"def"
		public Keyword getDefKeyword_3() { return cDefKeyword_3; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cBasicTypeAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cBaseTypeAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final CrossReference cBaseTypeTypeDeclCrossReference_0_1_0 = (CrossReference)cBaseTypeAssignment_0_1.eContents().get(0);
		private final RuleCall cBaseTypeTypeDeclIDTerminalRuleCall_0_1_0_1 = (RuleCall)cBaseTypeTypeDeclCrossReference_0_1_0.eContents().get(1);
		private final Alternatives cAlternatives_0_2 = (Alternatives)cGroup_0.eContents().get(2);
		private final Group cGroup_0_2_0 = (Group)cAlternatives_0_2.eContents().get(0);
		private final Action cListTypeBaseAction_0_2_0_0 = (Action)cGroup_0_2_0.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_0_2_0_1 = (Keyword)cGroup_0_2_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_0_2_0_2 = (Keyword)cGroup_0_2_0.eContents().get(2);
		private final Group cGroup_0_2_1 = (Group)cAlternatives_0_2.eContents().get(1);
		private final Action cSetTypeBaseAction_0_2_1_0 = (Action)cGroup_0_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_2_1_1 = (Keyword)cGroup_0_2_1.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_0_2_1_2 = (Keyword)cGroup_0_2_1.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLessThanSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cTupleTypeAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cElemTypesAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cElemTypesTypeParserRuleCall_1_2_0 = (RuleCall)cElemTypesAssignment_1_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cAsteriskKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cElemTypesAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cElemTypesTypeParserRuleCall_1_3_1_0 = (RuleCall)cElemTypesAssignment_1_3_1.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//Type:
		//	{BasicType} baseType=[TypeDecl] ({ListType.base=current} "[" "]" | {SetType.base=current} "{" "}")* | "<" {TupleType}
		//	elemTypes+=Type ("*" elemTypes+=Type)+ ">";
		public ParserRule getRule() { return rule; }

		//{BasicType} baseType=[TypeDecl] ({ListType.base=current} "[" "]" | {SetType.base=current} "{" "}")* | "<" {TupleType}
		//elemTypes+=Type ("*" elemTypes+=Type)+ ">"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{BasicType} baseType=[TypeDecl] ({ListType.base=current} "[" "]" | {SetType.base=current} "{" "}")*
		public Group getGroup_0() { return cGroup_0; }

		//{BasicType}
		public Action getBasicTypeAction_0_0() { return cBasicTypeAction_0_0; }

		//baseType=[TypeDecl]
		public Assignment getBaseTypeAssignment_0_1() { return cBaseTypeAssignment_0_1; }

		//[TypeDecl]
		public CrossReference getBaseTypeTypeDeclCrossReference_0_1_0() { return cBaseTypeTypeDeclCrossReference_0_1_0; }

		//ID
		public RuleCall getBaseTypeTypeDeclIDTerminalRuleCall_0_1_0_1() { return cBaseTypeTypeDeclIDTerminalRuleCall_0_1_0_1; }

		//({ListType.base=current} "[" "]" | {SetType.base=current} "{" "}")*
		public Alternatives getAlternatives_0_2() { return cAlternatives_0_2; }

		//{ListType.base=current} "[" "]"
		public Group getGroup_0_2_0() { return cGroup_0_2_0; }

		//{ListType.base=current}
		public Action getListTypeBaseAction_0_2_0_0() { return cListTypeBaseAction_0_2_0_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0_2_0_1() { return cLeftSquareBracketKeyword_0_2_0_1; }

		//"]"
		public Keyword getRightSquareBracketKeyword_0_2_0_2() { return cRightSquareBracketKeyword_0_2_0_2; }

		//{SetType.base=current} "{" "}"
		public Group getGroup_0_2_1() { return cGroup_0_2_1; }

		//{SetType.base=current}
		public Action getSetTypeBaseAction_0_2_1_0() { return cSetTypeBaseAction_0_2_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0_2_1_1() { return cLeftCurlyBracketKeyword_0_2_1_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_0_2_1_2() { return cRightCurlyBracketKeyword_0_2_1_2; }

		//"<" {TupleType} elemTypes+=Type ("*" elemTypes+=Type)+ ">"
		public Group getGroup_1() { return cGroup_1; }

		//"<"
		public Keyword getLessThanSignKeyword_1_0() { return cLessThanSignKeyword_1_0; }

		//{TupleType}
		public Action getTupleTypeAction_1_1() { return cTupleTypeAction_1_1; }

		//elemTypes+=Type
		public Assignment getElemTypesAssignment_1_2() { return cElemTypesAssignment_1_2; }

		//Type
		public RuleCall getElemTypesTypeParserRuleCall_1_2_0() { return cElemTypesTypeParserRuleCall_1_2_0; }

		//("*" elemTypes+=Type)+
		public Group getGroup_1_3() { return cGroup_1_3; }

		//"*"
		public Keyword getAsteriskKeyword_1_3_0() { return cAsteriskKeyword_1_3_0; }

		//elemTypes+=Type
		public Assignment getElemTypesAssignment_1_3_1() { return cElemTypesAssignment_1_3_1; }

		//Type
		public RuleCall getElemTypesTypeParserRuleCall_1_3_1_0() { return cElemTypesTypeParserRuleCall_1_3_1_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_1_4() { return cGreaterThanSignKeyword_1_4; }
	}

	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBasicLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTupleLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cListLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSetLiteralParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Literal:
		//	BasicLiteral | TupleLiteral | ListLiteral | SetLiteral;
		public ParserRule getRule() { return rule; }

		//BasicLiteral | TupleLiteral | ListLiteral | SetLiteral
		public Alternatives getAlternatives() { return cAlternatives; }

		//BasicLiteral
		public RuleCall getBasicLiteralParserRuleCall_0() { return cBasicLiteralParserRuleCall_0; }

		//TupleLiteral
		public RuleCall getTupleLiteralParserRuleCall_1() { return cTupleLiteralParserRuleCall_1; }

		//ListLiteral
		public RuleCall getListLiteralParserRuleCall_2() { return cListLiteralParserRuleCall_2; }

		//SetLiteral
		public RuleCall getSetLiteralParserRuleCall_3() { return cSetLiteralParserRuleCall_3; }
	}

	public class BasicLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BasicLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeConsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeConsTypeDeclCrossReference_0_0 = (CrossReference)cTypeConsAssignment_0.eContents().get(0);
		private final RuleCall cTypeConsTypeDeclIDTerminalRuleCall_0_0_1 = (RuleCall)cTypeConsTypeDeclCrossReference_0_0.eContents().get(1);
		private final Assignment cLitAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLitLITTerminalRuleCall_1_0 = (RuleCall)cLitAssignment_1.eContents().get(0);
		
		//BasicLiteral:
		//	typeCons=[TypeDecl] lit=LIT;
		public ParserRule getRule() { return rule; }

		//typeCons=[TypeDecl] lit=LIT
		public Group getGroup() { return cGroup; }

		//typeCons=[TypeDecl]
		public Assignment getTypeConsAssignment_0() { return cTypeConsAssignment_0; }

		//[TypeDecl]
		public CrossReference getTypeConsTypeDeclCrossReference_0_0() { return cTypeConsTypeDeclCrossReference_0_0; }

		//ID
		public RuleCall getTypeConsTypeDeclIDTerminalRuleCall_0_0_1() { return cTypeConsTypeDeclIDTerminalRuleCall_0_0_1; }

		//lit=LIT
		public Assignment getLitAssignment_1() { return cLitAssignment_1; }

		//LIT
		public RuleCall getLitLITTerminalRuleCall_1_0() { return cLitLITTerminalRuleCall_1_0; }
	}

	public class TupleLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TupleLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLessThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Action cTupleLiteralAction_1 = (Action)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cElemsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cElemsLiteralParserRuleCall_2_0_0 = (RuleCall)cElemsAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cElemsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cElemsLiteralParserRuleCall_2_1_1_0 = (RuleCall)cElemsAssignment_2_1_1.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//TupleLiteral:
		//	"<" {TupleLiteral} (elems+=Literal ("," elems+=Literal)*)? ">";
		public ParserRule getRule() { return rule; }

		//"<" {TupleLiteral} (elems+=Literal ("," elems+=Literal)*)? ">"
		public Group getGroup() { return cGroup; }

		//"<"
		public Keyword getLessThanSignKeyword_0() { return cLessThanSignKeyword_0; }

		//{TupleLiteral}
		public Action getTupleLiteralAction_1() { return cTupleLiteralAction_1; }

		//(elems+=Literal ("," elems+=Literal)*)?
		public Group getGroup_2() { return cGroup_2; }

		//elems+=Literal
		public Assignment getElemsAssignment_2_0() { return cElemsAssignment_2_0; }

		//Literal
		public RuleCall getElemsLiteralParserRuleCall_2_0_0() { return cElemsLiteralParserRuleCall_2_0_0; }

		//("," elems+=Literal)*
		public Group getGroup_2_1() { return cGroup_2_1; }

		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }

		//elems+=Literal
		public Assignment getElemsAssignment_2_1_1() { return cElemsAssignment_2_1_1; }

		//Literal
		public RuleCall getElemsLiteralParserRuleCall_2_1_1_0() { return cElemsLiteralParserRuleCall_2_1_1_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_3() { return cGreaterThanSignKeyword_3; }
	}

	public class ListLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ListLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeConsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeConsTypeDeclCrossReference_0_0 = (CrossReference)cTypeConsAssignment_0.eContents().get(0);
		private final RuleCall cTypeConsTypeDeclIDTerminalRuleCall_0_0_1 = (RuleCall)cTypeConsTypeDeclCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cElemsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cElemsELiteralParserRuleCall_2_0_0 = (RuleCall)cElemsAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cElemsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cElemsELiteralParserRuleCall_2_1_1_0 = (RuleCall)cElemsAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ListLiteral:
		//	typeCons=[TypeDecl] "[" (elems+=ELiteral ("," elems+=ELiteral)*)? "]";
		public ParserRule getRule() { return rule; }

		//typeCons=[TypeDecl] "[" (elems+=ELiteral ("," elems+=ELiteral)*)? "]"
		public Group getGroup() { return cGroup; }

		//typeCons=[TypeDecl]
		public Assignment getTypeConsAssignment_0() { return cTypeConsAssignment_0; }

		//[TypeDecl]
		public CrossReference getTypeConsTypeDeclCrossReference_0_0() { return cTypeConsTypeDeclCrossReference_0_0; }

		//ID
		public RuleCall getTypeConsTypeDeclIDTerminalRuleCall_0_0_1() { return cTypeConsTypeDeclIDTerminalRuleCall_0_0_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//(elems+=ELiteral ("," elems+=ELiteral)*)?
		public Group getGroup_2() { return cGroup_2; }

		//elems+=ELiteral
		public Assignment getElemsAssignment_2_0() { return cElemsAssignment_2_0; }

		//ELiteral
		public RuleCall getElemsELiteralParserRuleCall_2_0_0() { return cElemsELiteralParserRuleCall_2_0_0; }

		//("," elems+=ELiteral)*
		public Group getGroup_2_1() { return cGroup_2_1; }

		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }

		//elems+=ELiteral
		public Assignment getElemsAssignment_2_1_1() { return cElemsAssignment_2_1_1; }

		//ELiteral
		public RuleCall getElemsELiteralParserRuleCall_2_1_1_0() { return cElemsELiteralParserRuleCall_2_1_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}

	public class SetLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SetLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeConsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeConsTypeDeclCrossReference_0_0 = (CrossReference)cTypeConsAssignment_0.eContents().get(0);
		private final RuleCall cTypeConsTypeDeclIDTerminalRuleCall_0_0_1 = (RuleCall)cTypeConsTypeDeclCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cElemsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cElemsELiteralParserRuleCall_2_0_0 = (RuleCall)cElemsAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cElemsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cElemsELiteralParserRuleCall_2_1_1_0 = (RuleCall)cElemsAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//SetLiteral:
		//	typeCons=[TypeDecl] "{" (elems+=ELiteral ("," elems+=ELiteral)*)? "}";
		public ParserRule getRule() { return rule; }

		//typeCons=[TypeDecl] "{" (elems+=ELiteral ("," elems+=ELiteral)*)? "}"
		public Group getGroup() { return cGroup; }

		//typeCons=[TypeDecl]
		public Assignment getTypeConsAssignment_0() { return cTypeConsAssignment_0; }

		//[TypeDecl]
		public CrossReference getTypeConsTypeDeclCrossReference_0_0() { return cTypeConsTypeDeclCrossReference_0_0; }

		//ID
		public RuleCall getTypeConsTypeDeclIDTerminalRuleCall_0_0_1() { return cTypeConsTypeDeclIDTerminalRuleCall_0_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//(elems+=ELiteral ("," elems+=ELiteral)*)?
		public Group getGroup_2() { return cGroup_2; }

		//elems+=ELiteral
		public Assignment getElemsAssignment_2_0() { return cElemsAssignment_2_0; }

		//ELiteral
		public RuleCall getElemsELiteralParserRuleCall_2_0_0() { return cElemsELiteralParserRuleCall_2_0_0; }

		//("," elems+=ELiteral)*
		public Group getGroup_2_1() { return cGroup_2_1; }

		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }

		//elems+=ELiteral
		public Assignment getElemsAssignment_2_1_1() { return cElemsAssignment_2_1_1; }

		//ELiteral
		public RuleCall getElemsELiteralParserRuleCall_2_1_1_0() { return cElemsELiteralParserRuleCall_2_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class ELiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ELiteral");
		private final Assignment cLitAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLitLITTerminalRuleCall_0 = (RuleCall)cLitAssignment.eContents().get(0);
		
		//ELiteral:
		//	lit=LIT;
		public ParserRule getRule() { return rule; }

		//lit=LIT
		public Assignment getLitAssignment() { return cLitAssignment; }

		//LIT
		public RuleCall getLitLITTerminalRuleCall_0() { return cLitLITTerminalRuleCall_0; }
	}

	public class SubFeaturesDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SubFeaturesDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cCategoryNamesAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cCategoryNamesIDTerminalRuleCall_0_0_0 = (RuleCall)cCategoryNamesAssignment_0_0.eContents().get(0);
		private final Keyword cFullStopKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeSubFeaturesTypeParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//SubFeaturesDecl:
		//	(categoryNames+=ID ".")* name=ID type=SubFeaturesType;
		public ParserRule getRule() { return rule; }

		//(categoryNames+=ID ".")* name=ID type=SubFeaturesType
		public Group getGroup() { return cGroup; }

		//(categoryNames+=ID ".")*
		public Group getGroup_0() { return cGroup_0; }

		//categoryNames+=ID
		public Assignment getCategoryNamesAssignment_0_0() { return cCategoryNamesAssignment_0_0; }

		//ID
		public RuleCall getCategoryNamesIDTerminalRuleCall_0_0_0() { return cCategoryNamesIDTerminalRuleCall_0_0_0; }

		//"."
		public Keyword getFullStopKeyword_0_1() { return cFullStopKeyword_0_1; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//type=SubFeaturesType
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }

		//SubFeaturesType
		public RuleCall getTypeSubFeaturesTypeParserRuleCall_2_0() { return cTypeSubFeaturesTypeParserRuleCall_2_0; }
	}

	public class SubFeaturesTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SubFeaturesType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cColonKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Action cSubGroupTypeRefAction_0_1 = (Action)cGroup_0.eContents().get(1);
		private final Assignment cTypeAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final CrossReference cTypeFeaturesDeclCrossReference_0_2_0 = (CrossReference)cTypeAssignment_0_2.eContents().get(0);
		private final RuleCall cTypeFeaturesDeclIDTerminalRuleCall_0_2_0_1 = (RuleCall)cTypeFeaturesDeclCrossReference_0_2_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cSubGroupTypeAnonAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cLessThanSignColonKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cSupersAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final CrossReference cSupersFeaturesDeclCrossReference_1_1_1_0 = (CrossReference)cSupersAssignment_1_1_1.eContents().get(0);
		private final RuleCall cSupersFeaturesDeclIDTerminalRuleCall_1_1_1_0_1 = (RuleCall)cSupersFeaturesDeclCrossReference_1_1_1_0.eContents().get(1);
		private final Group cGroup_1_1_2 = (Group)cGroup_1_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_1_2_0 = (Keyword)cGroup_1_1_2.eContents().get(0);
		private final Assignment cSupersAssignment_1_1_2_1 = (Assignment)cGroup_1_1_2.eContents().get(1);
		private final CrossReference cSupersFeaturesDeclCrossReference_1_1_2_1_0 = (CrossReference)cSupersAssignment_1_1_2_1.eContents().get(0);
		private final RuleCall cSupersFeaturesDeclIDTerminalRuleCall_1_1_2_1_0_1 = (RuleCall)cSupersFeaturesDeclCrossReference_1_1_2_1_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cBodyAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cBodyFeaturesBodyParserRuleCall_1_3_0 = (RuleCall)cBodyAssignment_1_3.eContents().get(0);
		
		//SubFeaturesType:
		//	":" {SubGroupTypeRef} type=[FeaturesDecl] | {SubGroupTypeAnon} ("<:" supers+=[FeaturesDecl] (","
		//	supers+=[FeaturesDecl])*)? "=" body=FeaturesBody;
		public ParserRule getRule() { return rule; }

		//":" {SubGroupTypeRef} type=[FeaturesDecl] | {SubGroupTypeAnon} ("<:" supers+=[FeaturesDecl] (","
		//supers+=[FeaturesDecl])*)? "=" body=FeaturesBody
		public Alternatives getAlternatives() { return cAlternatives; }

		//":" {SubGroupTypeRef} type=[FeaturesDecl]
		public Group getGroup_0() { return cGroup_0; }

		//":"
		public Keyword getColonKeyword_0_0() { return cColonKeyword_0_0; }

		//{SubGroupTypeRef}
		public Action getSubGroupTypeRefAction_0_1() { return cSubGroupTypeRefAction_0_1; }

		//type=[FeaturesDecl]
		public Assignment getTypeAssignment_0_2() { return cTypeAssignment_0_2; }

		//[FeaturesDecl]
		public CrossReference getTypeFeaturesDeclCrossReference_0_2_0() { return cTypeFeaturesDeclCrossReference_0_2_0; }

		//ID
		public RuleCall getTypeFeaturesDeclIDTerminalRuleCall_0_2_0_1() { return cTypeFeaturesDeclIDTerminalRuleCall_0_2_0_1; }

		//{SubGroupTypeAnon} ("<:" supers+=[FeaturesDecl] ("," supers+=[FeaturesDecl])*)? "=" body=FeaturesBody
		public Group getGroup_1() { return cGroup_1; }

		//{SubGroupTypeAnon}
		public Action getSubGroupTypeAnonAction_1_0() { return cSubGroupTypeAnonAction_1_0; }

		//("<:" supers+=[FeaturesDecl] ("," supers+=[FeaturesDecl])*)?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"<:"
		public Keyword getLessThanSignColonKeyword_1_1_0() { return cLessThanSignColonKeyword_1_1_0; }

		//supers+=[FeaturesDecl]
		public Assignment getSupersAssignment_1_1_1() { return cSupersAssignment_1_1_1; }

		//[FeaturesDecl]
		public CrossReference getSupersFeaturesDeclCrossReference_1_1_1_0() { return cSupersFeaturesDeclCrossReference_1_1_1_0; }

		//ID
		public RuleCall getSupersFeaturesDeclIDTerminalRuleCall_1_1_1_0_1() { return cSupersFeaturesDeclIDTerminalRuleCall_1_1_1_0_1; }

		//("," supers+=[FeaturesDecl])*
		public Group getGroup_1_1_2() { return cGroup_1_1_2; }

		//","
		public Keyword getCommaKeyword_1_1_2_0() { return cCommaKeyword_1_1_2_0; }

		//supers+=[FeaturesDecl]
		public Assignment getSupersAssignment_1_1_2_1() { return cSupersAssignment_1_1_2_1; }

		//[FeaturesDecl]
		public CrossReference getSupersFeaturesDeclCrossReference_1_1_2_1_0() { return cSupersFeaturesDeclCrossReference_1_1_2_1_0; }

		//ID
		public RuleCall getSupersFeaturesDeclIDTerminalRuleCall_1_1_2_1_0_1() { return cSupersFeaturesDeclIDTerminalRuleCall_1_1_2_1_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_1_2() { return cEqualsSignKeyword_1_2; }

		//body=FeaturesBody
		public Assignment getBodyAssignment_1_3() { return cBodyAssignment_1_3; }

		//FeaturesBody
		public RuleCall getBodyFeaturesBodyParserRuleCall_1_3_0() { return cBodyFeaturesBodyParserRuleCall_1_3_0; }
	}
	
	
	private ModelElements pModel;
	private DeclElements pDecl;
	private TypeDeclElements pTypeDecl;
	private FeaturesDeclElements pFeaturesDecl;
	private FeaturesBodyElements pFeaturesBody;
	private FeatureDeclElements pFeatureDecl;
	private InvariantDeclElements pInvariantDecl;
	private MultiplicityInvariantDeclElements pMultiplicityInvariantDecl;
	private SubFeaturesMatchElements pSubFeaturesMatch;
	private ConstraintNatElements pConstraintNat;
	private AttrDeclElements pAttrDecl;
	private ModifierElements pModifier;
	private TypeElements pType;
	private LiteralElements pLiteral;
	private BasicLiteralElements pBasicLiteral;
	private TupleLiteralElements pTupleLiteral;
	private ListLiteralElements pListLiteral;
	private SetLiteralElements pSetLiteral;
	private ELiteralElements pELiteral;
	private SubFeaturesDeclElements pSubFeaturesDecl;
	private SubFeaturesTypeElements pSubFeaturesType;
	private TerminalRule tID;
	private TerminalRule tLIT;
	private TerminalRule tNAT;
	private TerminalRule tML_COMMENT;
	private TerminalRule tSL_COMMENT;
	private TerminalRule tWS;
	
	private final Grammar grammar;

	@Inject
	public DeviceModelingLanguageGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("edu.ksu.cis.projects.mdcf.devicemodel.DeviceModelingLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Model:
	//	decls+=Decl*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Decl:
	//	TypeDecl | FeaturesDecl;
	public DeclElements getDeclAccess() {
		return (pDecl != null) ? pDecl : (pDecl = new DeclElements());
	}
	
	public ParserRule getDeclRule() {
		return getDeclAccess().getRule();
	}

	//TypeDecl:
	//	"type" name=ID ("<:" supers+=[TypeDecl] ("," supers+=[TypeDecl])*)? ("{" (elems+=ELiteral ("," elems+=ELiteral)*)?
	//	"}")?;
	public TypeDeclElements getTypeDeclAccess() {
		return (pTypeDecl != null) ? pTypeDecl : (pTypeDecl = new TypeDeclElements());
	}
	
	public ParserRule getTypeDeclRule() {
		return getTypeDeclAccess().getRule();
	}

	//FeaturesDecl:
	//	complete="complete"? "features" name=ID ("<:" supers+=[FeaturesDecl] ("," supers+=[FeaturesDecl])*)?
	//	body=FeaturesBody;
	public FeaturesDeclElements getFeaturesDeclAccess() {
		return (pFeaturesDecl != null) ? pFeaturesDecl : (pFeaturesDecl = new FeaturesDeclElements());
	}
	
	public ParserRule getFeaturesDeclRule() {
		return getFeaturesDeclAccess().getRule();
	}

	//FeaturesBody:
	//	"{" {FeaturesBody} features+=FeatureDecl* "}";
	public FeaturesBodyElements getFeaturesBodyAccess() {
		return (pFeaturesBody != null) ? pFeaturesBody : (pFeaturesBody = new FeaturesBodyElements());
	}
	
	public ParserRule getFeaturesBodyRule() {
		return getFeaturesBodyAccess().getRule();
	}

	//FeatureDecl:
	//	InvariantDecl | AttrDecl | SubFeaturesDecl;
	public FeatureDeclElements getFeatureDeclAccess() {
		return (pFeatureDecl != null) ? pFeatureDecl : (pFeatureDecl = new FeatureDeclElements());
	}
	
	public ParserRule getFeatureDeclRule() {
		return getFeatureDeclAccess().getRule();
	}

	//InvariantDecl:
	//	MultiplicityInvariantDecl;
	public InvariantDeclElements getInvariantDeclAccess() {
		return (pInvariantDecl != null) ? pInvariantDecl : (pInvariantDecl = new InvariantDeclElements());
	}
	
	public ParserRule getInvariantDeclRule() {
		return getInvariantDeclAccess().getRule();
	}

	//MultiplicityInvariantDecl:
	//	"inv" (invName=ID ":")? (lo=ConstraintNat ".." hi=ConstraintNat) match=SubFeaturesMatch (":" type=[FeaturesDecl])?;
	public MultiplicityInvariantDeclElements getMultiplicityInvariantDeclAccess() {
		return (pMultiplicityInvariantDecl != null) ? pMultiplicityInvariantDecl : (pMultiplicityInvariantDecl = new MultiplicityInvariantDeclElements());
	}
	
	public ParserRule getMultiplicityInvariantDeclRule() {
		return getMultiplicityInvariantDeclAccess().getRule();
	}

	//SubFeaturesMatch:
	//	{SubFeaturesMatch} (categoryNames+=ID ".")* (name=ID | any="*");
	public SubFeaturesMatchElements getSubFeaturesMatchAccess() {
		return (pSubFeaturesMatch != null) ? pSubFeaturesMatch : (pSubFeaturesMatch = new SubFeaturesMatchElements());
	}
	
	public ParserRule getSubFeaturesMatchRule() {
		return getSubFeaturesMatchAccess().getRule();
	}

	//ConstraintNat:
	//	{NumNatConstraint} num=NAT | {AnyNatConstraint} "*";
	public ConstraintNatElements getConstraintNatAccess() {
		return (pConstraintNat != null) ? pConstraintNat : (pConstraintNat = new ConstraintNatElements());
	}
	
	public ParserRule getConstraintNatRule() {
		return getConstraintNatAccess().getRule();
	}

	//AttrDecl:
	//	modifier=Modifier attributeName=ID (":" type=Type | "=" literal=Literal);
	public AttrDeclElements getAttrDeclAccess() {
		return (pAttrDecl != null) ? pAttrDecl : (pAttrDecl = new AttrDeclElements());
	}
	
	public ParserRule getAttrDeclRule() {
		return getAttrDeclAccess().getRule();
	}

	//Modifier:
	//	"const" | "val" | "var" | "def";
	public ModifierElements getModifierAccess() {
		return (pModifier != null) ? pModifier : (pModifier = new ModifierElements());
	}
	
	public ParserRule getModifierRule() {
		return getModifierAccess().getRule();
	}

	//Type:
	//	{BasicType} baseType=[TypeDecl] ({ListType.base=current} "[" "]" | {SetType.base=current} "{" "}")* | "<" {TupleType}
	//	elemTypes+=Type ("*" elemTypes+=Type)+ ">";
	public TypeElements getTypeAccess() {
		return (pType != null) ? pType : (pType = new TypeElements());
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//Literal:
	//	BasicLiteral | TupleLiteral | ListLiteral | SetLiteral;
	public LiteralElements getLiteralAccess() {
		return (pLiteral != null) ? pLiteral : (pLiteral = new LiteralElements());
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}

	//BasicLiteral:
	//	typeCons=[TypeDecl] lit=LIT;
	public BasicLiteralElements getBasicLiteralAccess() {
		return (pBasicLiteral != null) ? pBasicLiteral : (pBasicLiteral = new BasicLiteralElements());
	}
	
	public ParserRule getBasicLiteralRule() {
		return getBasicLiteralAccess().getRule();
	}

	//TupleLiteral:
	//	"<" {TupleLiteral} (elems+=Literal ("," elems+=Literal)*)? ">";
	public TupleLiteralElements getTupleLiteralAccess() {
		return (pTupleLiteral != null) ? pTupleLiteral : (pTupleLiteral = new TupleLiteralElements());
	}
	
	public ParserRule getTupleLiteralRule() {
		return getTupleLiteralAccess().getRule();
	}

	//ListLiteral:
	//	typeCons=[TypeDecl] "[" (elems+=ELiteral ("," elems+=ELiteral)*)? "]";
	public ListLiteralElements getListLiteralAccess() {
		return (pListLiteral != null) ? pListLiteral : (pListLiteral = new ListLiteralElements());
	}
	
	public ParserRule getListLiteralRule() {
		return getListLiteralAccess().getRule();
	}

	//SetLiteral:
	//	typeCons=[TypeDecl] "{" (elems+=ELiteral ("," elems+=ELiteral)*)? "}";
	public SetLiteralElements getSetLiteralAccess() {
		return (pSetLiteral != null) ? pSetLiteral : (pSetLiteral = new SetLiteralElements());
	}
	
	public ParserRule getSetLiteralRule() {
		return getSetLiteralAccess().getRule();
	}

	//ELiteral:
	//	lit=LIT;
	public ELiteralElements getELiteralAccess() {
		return (pELiteral != null) ? pELiteral : (pELiteral = new ELiteralElements());
	}
	
	public ParserRule getELiteralRule() {
		return getELiteralAccess().getRule();
	}

	//SubFeaturesDecl:
	//	(categoryNames+=ID ".")* name=ID type=SubFeaturesType;
	public SubFeaturesDeclElements getSubFeaturesDeclAccess() {
		return (pSubFeaturesDecl != null) ? pSubFeaturesDecl : (pSubFeaturesDecl = new SubFeaturesDeclElements());
	}
	
	public ParserRule getSubFeaturesDeclRule() {
		return getSubFeaturesDeclAccess().getRule();
	}

	//SubFeaturesType:
	//	":" {SubGroupTypeRef} type=[FeaturesDecl] | {SubGroupTypeAnon} ("<:" supers+=[FeaturesDecl] (","
	//	supers+=[FeaturesDecl])*)? "=" body=FeaturesBody;
	public SubFeaturesTypeElements getSubFeaturesTypeAccess() {
		return (pSubFeaturesType != null) ? pSubFeaturesType : (pSubFeaturesType = new SubFeaturesTypeElements());
	}
	
	public ParserRule getSubFeaturesTypeRule() {
		return getSubFeaturesTypeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal LIT:
	//	"("->")";
	public TerminalRule getLITRule() {
		return (tLIT != null) ? tLIT : (tLIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LIT"));
	} 

	//terminal NAT:
	//	"0" | "1".."9" "0".."9"*;
	public TerminalRule getNATRule() {
		return (tNAT != null) ? tNAT : (tNAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NAT"));
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return (tML_COMMENT != null) ? tML_COMMENT : (tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ML_COMMENT"));
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return (tSL_COMMENT != null) ? tSL_COMMENT : (tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT"));
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return (tWS != null) ? tWS : (tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS"));
	} 
}
